# Generated by Django 4.2.1 on 2023-05-11 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0003_alter_city_options_alter_state_options'),
        ('attraction', '0002_categoryrestaurant_touristspot_alter_hotel_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PackageAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_start', models.DateField()),
                ('tour_end', models.DateField()),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='attraction.attraction')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='package.package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='attractions',
            field=models.ManyToManyField(through='package.PackageAttraction', to='attraction.attraction'),
        ),
        migrations.AddField(
            model_name='package',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities_package', to='city.city'),
        ),
    ]
