# Generated by Django 4.2.1 on 2023-05-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='clients',
            field=models.ManyToManyField(to='client.client'),
        ),
    ]
