# Generated by Django 4.2.1 on 2023-05-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('package', '0002_package_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='clients',
            field=models.ManyToManyField(blank=True, to='client.client'),
        ),
    ]
