# Generated by Django 4.2.1 on 2023-05-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0004_alter_hotel_restaurant_hotel'),
        ('package', '0003_alter_package_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotels_package', to='attraction.hotel'),
            preserve_default=False,
        ),
    ]
