# Generated by Django 4.2.1 on 2023-05-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_package_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packageattraction',
            old_name='tour_end',
            new_name='visitation_date',
        ),
        migrations.RemoveField(
            model_name='packageattraction',
            name='tour_start',
        ),
    ]
