# Generated by Django 4.2.1 on 2023-05-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('package', '0005_rename_tour_end_packageattraction_visitation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='client_packages', to='client.client'),
        ),
    ]
