# Generated by Django 4.2.1 on 2023-05-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_state_city_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',), 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('name',)},
        ),
    ]
