# Generated by Django 4.2.1 on 2023-05-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_alter_city_options_alter_state_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
