# Generated by Django 4.2.1 on 2023-05-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_city_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.IntegerField(default=2000000),
            preserve_default=False,
        ),
    ]
