# Generated by Django 4.2.1 on 2023-05-11 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('attraction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attraction.attraction')),
                ('description', models.CharField(max_length=100)),
            ],
            bases=('attraction.attraction',),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_hotel', to='attraction.categoryhotel'),
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('touristspot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attraction.touristspot')),
                ('construction_date', models.DateField()),
                ('construction_style', models.CharField(max_length=50)),
            ],
            bases=('attraction.touristspot',),
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('touristspot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attraction.touristspot')),
                ('number_rooms', models.IntegerField()),
                ('foundation_date', models.DateField()),
            ],
            bases=('attraction.touristspot',),
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('touristspot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attraction.touristspot')),
                ('type', models.CharField(max_length=15)),
            ],
            bases=('attraction.touristspot',),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('attraction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attraction.attraction')),
                ('name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_restaurant', to='attraction.categoryrestaurant')),
            ],
            bases=('attraction.attraction',),
        ),
        migrations.AddField(
            model_name='hotel',
            name='restaurant_hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants_hotel', to='attraction.restaurant'),
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField()),
                ('nationality', models.CharField(max_length=15)),
                ('professional_activity', models.CharField(max_length=15)),
                ('museums', models.ManyToManyField(to='attraction.museum')),
            ],
        ),
        migrations.CreateModel(
            name='ConcertHall',
            fields=[
                ('touristspot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attraction.touristspot')),
                ('start_time', models.TimeField()),
                ('closing_day', models.DateField()),
                ('restaurant_hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants_hall', to='attraction.restaurant')),
            ],
            bases=('attraction.touristspot',),
        ),
    ]
