# Generated by Django 4.2.1 on 2023-05-12 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0003_alter_concerthall_restaurant_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='restaurant_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants_hotel', to='attraction.restaurant'),
        ),
    ]
