# Generated by Django 4.2.1 on 2023-05-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0004_alter_hotel_restaurant_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='type_attraction',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='touristspot',
            name='type_tourist_spot',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
