# Generated by Django 4.2.1 on 2023-05-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0005_attraction_type_attraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='quantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
