# Generated by Django 4.2.1 on 2023-05-18 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0007_alter_concerthall_closing_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concerthall',
            name='restaurant_hall',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants_hall', to='attraction.restaurant'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='restaurant_hotel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants_hotel', to='attraction.restaurant'),
        ),
    ]
