# Generated by Django 4.2.1 on 2023-05-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0008_alter_concerthall_restaurant_hall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='name',
            field=models.CharField(default='name default', max_length=100),
            preserve_default=False,
        ),
    ]
