# Generated by Django 4.2.1 on 2023-05-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0009_touristspot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
