# Generated by Django 4.2.1 on 2023-05-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0010_alter_touristspot_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
